### ISSUE TITLE
how to set SetSegmentedIndex

### ISSUE THREAD

**Issue by darshanpatel9773** [lijingcheng/JCSegmentBarController#1]
I am using JCSegmentedBarController and i have 3 view controller declared in appdelegate.
But when app launch by default now its loads with the view controller at index 0, but i want to load the view controller at index 1 when app launch. Please help me how to set the default index of JCSegmentedBarController.

**Comment by lijingcheng** [comment]
@darshanpatel9773 sorry, just saw your insues, after updating the code can use selectedIndex property settings

**Comment by darshanpatel9773** [comment]
@lijingcheng Thanks
