### ISSUE TITLE
Cannot pull to request

### ISSUE THREAD

**Issue by damthieuquang** [lijingcheng/JCSegmentBarController#4]
Hi @lijingcheng,

The first words I want to say your lib so quit good when I use in my project. But, when I use it, I must implement something suitable my requirement in project and I think it will be useful for your lib.

Unfortunately, I can't create new pull to request from your repository. Can you allow me to create new pull to request by creating new branch?

**Comment by lijingcheng** [comment]
Hi @damthieuquang 
thanks, i have created the develop branch :)

**Comment by damthieuquang** [comment]
Thanks @lijingcheng
